# Generated by Django 3.0.2 on 2020-12-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_bankaccounttype_color_code'),
        ('accounts', '0009_auto_20201107_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_for',
            field=models.ManyToManyField(blank=True, null=True, to='company.Company'),
        ),
    ]
