EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mathegeniuse@gmail.com'
EMAIL_HOST_PASSWORD = "K1ngL1verp00l"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "mathegeniuse@gmail.com"
SUPPORT_EMAIL = "mathegeniuse@gmail.com"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "AMJU LOANS"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
SENDGRID_API_KEY = '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'
