# Generated by Django 3.0.2 on 2020-12-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_loanrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequests',
            name='duration_figure',
            field=models.IntegerField(default=1),
        ),
    ]
