# Generated by Django 3.0.2 on 2020-12-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201212_0534'),
        ('borrowers', '0010_borrowergroup_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
