# Generated by Django 3.0.2 on 2020-12-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bankcode_otp_enabled'),
        ('borrowers', '0011_borrower_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.BankCode'),
        ),
    ]
