# Generated by Django 3.0.2 on 2020-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0012_auto_20201212_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
