# Generated by Django 3.0.2 on 2021-01-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0013_borrower_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='card_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='expiry_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='expiry_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
