# Generated by Django 3.0.2 on 2021-01-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0015_auto_20210112_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
