# Generated by Django 3.0.2 on 2021-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0016_auto_20210113_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='bank_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='country_text',
            field=models.CharField(blank=True, default='Nigeria', max_length=255, null=True),
        ),
    ]
