# Generated by Django 3.0.2 on 2021-03-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0017_auto_20210127_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='title',
            field=models.CharField(blank=True, default='Mr', max_length=255, null=True),
        ),
    ]
